### ISSUE TITLE
Add wave shader to leafs

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/nodebox_trees#8]
@D00Med aperenly in the newest version of minetest they added the ability to have the waving shader on nodeboxes and models

The waving shuld only happen when the waving shader is enabled in the settings

**Comment by tobyplowy** [comment]
@D00Med NOTE this should only happen on leafs not coral

**Comment by D00Med** [comment]
@tobyplowy  Ok, I'm working on it.

**Comment by D00Med** [comment]
@tobyplowy Ok, it's done :)

**Comment by tobyplowy** [comment]
Nice!

**Comment by tobyplowy** [comment]
@D00Med Can you also post a Forum update?

**Comment by D00Med** [comment]
@tobyplowy Already done :)
I've also been working on an update to Legend of Minetest.

**Comment by tobyplowy** [comment]
Cool :)

**Comment by tobyplowy** [comment]
@D00Med hey do you still want to work on that wastland subgame you mentioned?

**Comment by D00Med** [comment]
@tobyplowy I already have enough to do :'D

**Comment by tobyplowy** [comment]
Lol

**Comment by D00Med** [comment]
@tobyplowy I really want to see farlands finished, v1 at least.

**Comment by tobyplowy** [comment]
@D00Med Yes next week we will get at it again :)

**Comment by tobyplowy** [comment]
@D00Med theres already stuff that you can do 

Maybe you can start working on the simple electricity sistem

Also the Dinos may need to be scraped for v1 and instead be added in v2?

**Comment by D00Med** [comment]
@tobyplowy Yeah :) I'm going to do a little work on it this week too. 
Yeah. idk, up to you.
I've actually got to go now, so enjoy the rest of your evening :)

**Comment by tobyplowy** [comment]
@D00Med Yes you too (sorry for the late reply)
